// Экспорт функций базы данных
import {
  initDatabase,
  getMaps,
  addMap,
  deleteMap,
  getSides,
  addSide,
  deleteSide,
  getDifficulties,
  addDifficulty,
  deleteDifficulty,
  getLines,
  addLine,
  deleteLine,
  getGrenadeTypes,
  addGrenadeType,
  deleteGrenadeType,
  getSmokesByMap,
  addSmoke,
  saveSmokeImage,
  getSmokeMedia,
  deleteSmoke,
  getSmokeById,
  clearAllSmokes,
  getAllSmokes,
} from './database';

export {
  initDatabase,
  getMaps,
  addMap,
  deleteMap,
  getSides,
  addSide,
  deleteSide,
  getDifficulties,
  addDifficulty,
  deleteDifficulty,
  getLines,
  addLine,
  deleteLine,
  getGrenadeTypes,
  addGrenadeType,
  deleteGrenadeType,
  getSmokesByMap,
  addSmoke,
  saveSmokeImage,
  getSmokeMedia,
  deleteSmoke,
  getSmokeById,
  clearAllSmokes,
  getAllSmokes,
};